project:
  type: website
  output-dir: docs
  resources:
    - googlef635b60f6d83e826.html

website:
  title: "Olivia Roberts"
  description: "Personal website of Olivia Kaitlyn Roberts (Olivia K Roberts)."
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: tobacco-project.qmd
        text: Tobacco Use Project
        
      - href: about-data.qmd
        text: About the Data

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

